---

- name: Bootstrapping developer environment
  hosts: localhost
  remote_user: vagrant
  vars:
    github_known_hosts_line: "github.com,ssh.github.com,192.30.252.151,192.30.252.148 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="

  tasks:

  - name: Install kernel extras
    sudo: yes
    apt: >
      pkg="linux-image-extra-{{ ansible_kernel }}"
      state=present
      update_cache=yes 
      cache_valid_time=3600

  - name: Install aufs kernel module
    sudo: yes
    modprobe: name=aufs state=present

  - name: Install helpful packages
    sudo: yes
    apt: >
      pkg={{ item }}
      state=present 
      update_cache=yes 
      cache_valid_time=3600
    with_items:
    - git
    - tmux
    - htop
    - socat
    - vim
    - vim-scripts
    - vim-puppet

  - name: Create directories
    sudo: yes
    file: >
      path={{ item.dir }}
      state=directory 
      owner={{ item.o }}
      group={{ item.g }}
    with_items:
    - { o: "vagrant", g: "vagrant", dir: "/data" }
    - { o: "vagrant", g: "vagrant", dir: "/data/sysroot" }
    - { o: "vagrant", g: "vagrant", dir: "/data/sysroot/home" }
    - { o: "vagrant", g: "vagrant", dir: "/data/sysroot/home/vagrant" }

  - name: Install SSH files
    copy: >
      src=/vagrant/.data/ssh/{{ item.file }}
      dest=/home/{{ ansible_ssh_user }}/.ssh/{{ item.file }}
      mode={{ item.mode }}
      owner={{ ansible_ssh_user }}
      group={{ ansible_ssh_user }}
    with_items:
    - { file: "config",     mode: "0600" }
    - { file: "github.pub", mode: "0600" }
    - { file: "github",     mode: "0400" }

  - name: Add github.com to known_hosts file
    lineinfile: >
      dest=/home/{{ ansible_ssh_user }}/.ssh/known_hosts
      regexp="^{{ item.host }}"
      line="{{ item.line }}"
      create=yes
    with_items:
    - host: github.com
      line: "{{ github_known_hosts_line }}"

  - name: Clone home repo
    git: >
      repo=ssh://github.com/themattrix/home.git
      dest=/data/home
      update=no

  - name: Create overlayed home directory
    sudo: yes
    mount: >
      name=/home/vagrant
      src=none
      fstype=aufs
      state=mounted
      opts="br=/data/sysroot/home/vagrant=rw:/data/home=rw:/home/vagrant"

  - name: Grab the current git configuration
    shell: git config --list
    register: git_config

  - name: Set global git config options
    shell: git config --global {{ item.opt }} "{{ item.value }}"
    when: not '{{ item.opt }}={{ item.value }}' in git_config.stdout_lines 
    with_items:
    - opt: user.name
      value: Matthew Tardiff
    - opt: user.email
      value: mattrix@gmail.com
    - opt: core.editor
      value: vim
    - opt: merge.tool
      value: vimdiff
    - opt: color.ui
      value: true

  - name: Install pathogen
    git: >
      repo=https://github.com/tpope/vim-pathogen.git
      dest=/home/{{ ansible_ssh_user }}/.vim
      update=no

  - name: Install vim plugins
    git: >
      repo={{ item.repo }}
      dest=/home/{{ ansible_ssh_user }}/.vim/bundle/{{ item.name }}
      update=no
    with_items:
    - name: vim-colorschemes
      repo: https://github.com/flazz/vim-colorschemes.git
    - name: vim-colorscheme-switcher
      repo: https://github.com/vim-scripts/vim-colorscheme-switcher.git
    - name: vim-misc
      repo: https://github.com/xolox/vim-misc.git
    - name: supertab
      repo: https://github.com/ervandew/supertab.git
    - name: vim-colors-solarized-brown
      repo: https://github.com/ajacksified/vim-colors-solarized-brown.git
    - name: vim-easy-align
      repo: https://github.com/junegunn/vim-easy-align.git
    - name: vim-surround
      repo: https://github.com/tpope/vim-surround.git
    - name: vim-tmux-navigator
      repo: https://github.com/christoomey/vim-tmux-navigator.git
    - name: vim-yaml
      repo: https://github.com/stephpy/vim-yaml.git

  - name: Clone dircolors-solarized
    git: repo={{ item.repo }} dest=/data/{{ item.name }} update=no
    with_items:
    - name: dircolors-solarized
      repo: https://github.com/seebi/dircolors-solarized.git

  - name: Link dircolors-solarized dark
    file: >
      path="/home/{{ ansible_ssh_user }}/.dircolors"
      src="/data/dircolors-solarized/dircolors.256dark"
      state=link
