---

- name: Bootstrapping developer environment
  hosts: localhost

  tasks:

  - name: Installing helpful packages
    apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
    with_items:
    - vim
    - git
    - tmux
    - htop
    - socat
