---

- name: Bootstrapping developer environment
  hosts: localhost
  remote_user: vagrant

  tasks:

  - name: Installing helpful packages
    sudo: yes
    apt: >
      pkg={{ item }} 
      state=present 
      update_cache=yes 
      cache_valid_time=3600
    with_items:
    - vim
    - git
    - tmux
    - htop
    - socat

  - name: Create data dir
    sudo: yes
    file: >
      path=/data 
      state=directory 
      owner=vagrant 
      group=vagrant

  - name: Install SSH files
    copy: >
      src=/vagrant/.data/ssh/{{ item.file }}
      dest=/home/{{ ansible_ssh_user }}/.ssh/{{ item.file }}
      mode={{ item.mode }}
      owner={{ ansible_ssh_user }}
      group={{ ansible_ssh_user }}
    with_items:
    - { "file": "config",     "mode": "0600" }
    - { "file": "github.pub", "mode": "0600" }
    - { "file": "github",     "mode": "0400" }

  - name: Add github.com to known_hosts file
    lineinfile: >
      dest=/home/{{ ansible_ssh_user }}/.ssh/known_hosts
      regexp="^{{ item.host }}"
      line="{{ item.line }}"
    with_items:
    - { "host": "github.com", "line": "github.com,ssh.github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" }

  - name: Clone home repo
    git: >
      repo=ssh://github.com/themattrix/home.git
      dest=/data/home
