---

- name: Install pathogen
  git: >
    repo="https://github.com/tpope/vim-pathogen.git"
    dest="/home/{{ ansible_ssh_user }}/.vim"
    update=no

- name: Install vim plugins
  git: >
    repo="{{ item }}.git"
    dest="/home/{{ ansible_ssh_user }}/.vim/bundle/{{ item | basename }}"
    update=no
  with_items:

  # General-purpose tools
  - https://github.com/xolox/vim-misc
  - https://github.com/ervandew/supertab
  - https://github.com/junegunn/vim-easy-align
  - https://github.com/tpope/vim-surround
  - https://github.com/tpope/vim-sensible
  - https://github.com/christoomey/vim-tmux-navigator
  - https://github.com/kien/ctrlp.vim
  - https://github.com/Lokaltog/vim-easymotion
  - https://github.com/sjl/gundo.vim
  - https://github.com/mileszs/ack.vim    # requires the 'ack-grep' package
  - https://github.com/ciaranm/detectindent
  - https://github.com/tomtom/tcomment_vim

  # Colors
  - https://github.com/flazz/vim-colorschemes
  - https://github.com/vim-scripts/vim-colorscheme-switcher
  - https://github.com/tomasr/molokai

  # Git tools
  - https://github.com/tpope/vim-fugitive

  # Yaml tools
  - https://github.com/stephpy/vim-yaml

  # Puppet tools
  - https://github.com/rodjek/vim-puppet

  # C/C++ tools
  - https://github.com/Rip-Rip/clang_complete

  # Docker tools
  - https://github.com/ekalinin/Dockerfile.vim
