---

- name: Install helpful packages
  sudo: yes
  apt: >
    pkg={{ item }}
    state=present 
    update_cache=yes 
    cache_valid_time=3600
  with_items:
  - git
  - tmux
  - htop
  - socat
  - vim
  - vim-scripts
  - vim-puppet
