---

- name: Install kernel extras
  sudo: yes
  apt: >
    pkg="linux-image-extra-{{ ansible_kernel }}"
    state=present
    update_cache=yes 
    cache_valid_time=3600

- name: Install aufs kernel module
  sudo: yes
  modprobe: name=aufs state=present
