---

- name: Create overlayed home directory
  sudo: yes
  mount: >
    name=/home/vagrant
    src=none
    fstype=aufs
    state=mounted
    opts="br=/data/sysroot/home/vagrant:/data/home:/home/vagrant"

